version: "3.8"
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: fa_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: fa_user
      POSTGRES_PASSWORD: fa_pass
      POSTGRES_DB: fa_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db_data:
